### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by mindplay-dk** [marcj/topsort.php#1]
Any particular reason this isn't 1.0 yet?

Appears to be complete, tested and dependable. Are you planning any changes that require a BC break? If not, I would feel better about using a tagged release :-)

**Comment by marcj** [comment]
Et Voilà: https://github.com/marcj/topsort.php/releases/tag/1.0.0

You're right, its pretty stable and I don't expect any BC breaks, because it's actually pretty complete already.

**Comment by mindplay-dk** [comment]
Brilliant, thanks! :-)
