### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by sminnee** [marcj/topsort.php#8]
In line 16 of https://github.com/marcj/topsort.php/blob/master/src/CircularDependencyException.php, $nodes has no default value but the first 3 arguments do.

In PHP 8, this creates a warning:
> Required parameter $nodes follows optional parameter $message

**Comment by sminnee** [comment]
Would you accept a patch that made $nodes optional via `$nodes = null`? I can't make none of the arguments arguments optional without throwing a subclass error.

In such a case I would assume:
 * getStart() returns null
 * getEnd() returns null
 * getNodes() returns []

Does that seem reasonable?

Arguably the constructor could be made private, forcing users to use create, although that's probably a breaking change?

**Comment by marcj** [comment]
Absolutely, if you provide one without BC breaks I'm going to merge and tag soon.🙏

**Comment by marcj** [comment]
The best is probably to make either all args required, or if that doesn't work make $nodes default to empty array.

**Comment by sminnee** [comment]
~~That throws an error because it breaks compatibility with the parent constructor. I can set `$nodes = []` in the method signature. getStart() and getEnd() will still return null, though, and the constructor will need some special treatment of an empty array.~~

~~Sound good?~~

Turns out you can do this on constructors, just not non-constructor methods. Hurray, consistency! I'll make all of the arguments required, then.

**Comment by marcj** [comment]
hehe, good thing I don't do PHP anymore. Great! You can add php8 to travis as well if you want (if thats available, I don't know🤷‍♂️)

**Comment by sminnee** [comment]
Yeah I was going to try and do that. I'm a little blocked by the version of PHPUnit you're using (which is necessary to support the older versions of PHP)

One option would be to branch off a 2.x release that supports PHP >= 7.3 and move to PHPUnit 9 with that.

PHP 7.2 goes EOL in a couple of months so maybe it's okay to leave the 1.1.0 version for that.

If I put together a PR that dropped support for PHP 5.4 - 7.2, would you be open to merging it and tagging 2.0.0? Or do you think that no API breakages other than dropping older versions of PHP is appropriate in a 1.2.0 release?

**Comment by marcj** [comment]
> If I put together a PR that dropped support for PHP 5.4 - 7.2, would you be open to merging it and tagging 2.0.0?

Yeah, let's do that.

**Comment by sminnee** [comment]
Cheers! I'll try raise a PR in the next few days.
